AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  feed

  Sample SAM Template for feed

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 8

Resources:
  FeedFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: feed/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        Feed:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /feed
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FeedApi:
    Description: "API Gateway endpoint URL for Prod stage for Feed function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/feed/"
  FeedFunction:
    Description: "Feed Lambda Function ARN"
    Value: !GetAtt FeedFunction.Arn
  FeedFunctionIamRole:
    Description: "Implicit IAM Role created for Feed function"
    Value: !GetAtt FeedFunctionRole.Arn
