version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "y"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yjcatvser5u1"
s3_prefix = "y"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
